// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/product.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 响应状态码定义
type ResponseCode int32

const (
	ResponseCode_SUCCESS            ResponseCode = 0    // 成功
	ResponseCode_INTERNAL_ERROR     ResponseCode = 500  // 内部错误
	ResponseCode_INVALID_PARAM      ResponseCode = 400  // 参数错误
	ResponseCode_NOT_FOUND          ResponseCode = 404  // 资源不找到
	ResponseCode_CONFLICT           ResponseCode = 409  // 资源冲突（例如乐观锁冲突）
	ResponseCode_INSUFFICIENT_STOCK ResponseCode = 4001 // 库存不足
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0:    "SUCCESS",
		500:  "INTERNAL_ERROR",
		400:  "INVALID_PARAM",
		404:  "NOT_FOUND",
		409:  "CONFLICT",
		4001: "INSUFFICIENT_STOCK",
	}
	ResponseCode_value = map[string]int32{
		"SUCCESS":            0,
		"INTERNAL_ERROR":     500,
		"INVALID_PARAM":      400,
		"NOT_FOUND":          404,
		"CONFLICT":           409,
		"INSUFFICIENT_STOCK": 4001,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_product_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_proto_product_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{0}
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应码，0表示成功，非0表示错误
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 响应信息，成功或错误描述
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`  // 响应数据，可以是任何类型的序列化数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BaseResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateStockWithCASRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Deta          int64                  `protobuf:"varint,2,opt,name=deta,proto3" json:"deta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockWithCASRequest) Reset() {
	*x = UpdateStockWithCASRequest{}
	mi := &file_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockWithCASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockWithCASRequest) ProtoMessage() {}

func (x *UpdateStockWithCASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockWithCASRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockWithCASRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStockWithCASRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStockWithCASRequest) GetDeta() int64 {
	if x != nil {
		return x.Deta
	}
	return 0
}

type UpdateStockWithCASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"` // 基础响应信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockWithCASResponse) Reset() {
	*x = UpdateStockWithCASResponse{}
	mi := &file_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockWithCASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockWithCASResponse) ProtoMessage() {}

func (x *UpdateStockWithCASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockWithCASResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockWithCASResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStockWithCASResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

// 产品详细信息
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetProductListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` // 指定商品ID列表（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListRequest) Reset() {
	*x = GetProductListRequest{}
	mi := &file_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListRequest) ProtoMessage() {}

func (x *GetProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListRequest.ProtoReflect.Descriptor instead.
func (*GetProductListRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductListRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetProductListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`         // 基础响应信息
	Products      []*Product             `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"` // 商品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListResponse) Reset() {
	*x = GetProductListResponse{}
	mi := &file_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListResponse) ProtoMessage() {}

func (x *GetProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListResponse.ProtoReflect.Descriptor instead.
func (*GetProductListResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductListResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetProductListResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateProductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category         string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Price            int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Desc             string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Stock            int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	PicInfo          string                 `protobuf:"bytes,6,opt,name=picInfo,proto3" json:"picInfo,omitempty"`
	Dimensions       string                 `protobuf:"bytes,7,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Material         string                 `protobuf:"bytes,8,opt,name=material,proto3" json:"material,omitempty"`
	Weight           string                 `protobuf:"bytes,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Capacity         string                 `protobuf:"bytes,10,opt,name=capacity,proto3" json:"capacity,omitempty"`
	CareInstructions string                 `protobuf:"bytes,11,opt,name=careInstructions,proto3" json:"careInstructions,omitempty"`
	LatestEditorId   int32                  `protobuf:"varint,12,opt,name=latestEditorId,proto3" json:"latestEditorId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateProductRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductRequest) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *CreateProductRequest) GetDimensions() string {
	if x != nil {
		return x.Dimensions
	}
	return ""
}

func (x *CreateProductRequest) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *CreateProductRequest) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *CreateProductRequest) GetCapacity() string {
	if x != nil {
		return x.Capacity
	}
	return ""
}

func (x *CreateProductRequest) GetCareInstructions() string {
	if x != nil {
		return x.CareInstructions
	}
	return ""
}

func (x *CreateProductRequest) GetLatestEditorId() int32 {
	if x != nil {
		return x.LatestEditorId
	}
	return 0
}

type CreateProductResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Base             *BaseResponse          `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category         string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Price            int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Desc             string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Stock            int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	PicInfo          string                 `protobuf:"bytes,6,opt,name=picInfo,proto3" json:"picInfo,omitempty"`
	Dimensions       string                 `protobuf:"bytes,7,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Material         string                 `protobuf:"bytes,8,opt,name=material,proto3" json:"material,omitempty"`
	Weight           string                 `protobuf:"bytes,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Capacity         string                 `protobuf:"bytes,10,opt,name=capacity,proto3" json:"capacity,omitempty"`
	CareInstructions string                 `protobuf:"bytes,11,opt,name=careInstructions,proto3" json:"careInstructions,omitempty"`
	Id               int64                  `protobuf:"varint,12,opt,name=id,proto3" json:"id,omitempty"`
	LatestEditorId   int32                  `protobuf:"varint,13,opt,name=latestEditorId,proto3" json:"latestEditorId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_proto_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateProductResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductResponse) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *CreateProductResponse) GetDimensions() string {
	if x != nil {
		return x.Dimensions
	}
	return ""
}

func (x *CreateProductResponse) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *CreateProductResponse) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *CreateProductResponse) GetCapacity() string {
	if x != nil {
		return x.Capacity
	}
	return ""
}

func (x *CreateProductResponse) GetCareInstructions() string {
	if x != nil {
		return x.CareInstructions
	}
	return ""
}

func (x *CreateProductResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateProductResponse) GetLatestEditorId() int32 {
	if x != nil {
		return x.LatestEditorId
	}
	return 0
}

var File_proto_product_proto protoreflect.FileDescriptor

const file_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x13proto/product.proto\x12\tproductpb\"H\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"?\n" +
	"\x19UpdateStockWithCASRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04deta\x18\x02 \x01(\x03R\x04deta\"I\n" +
	"\x1aUpdateStockWithCASResponse\x12+\n" +
	"\x04base\x18\x01 \x01(\v2\x17.productpb.BaseResponseR\x04base\"q\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\")\n" +
	"\x15GetProductListRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"u\n" +
	"\x16GetProductListResponse\x12+\n" +
	"\x04base\x18\x01 \x01(\v2\x17.productpb.BaseResponseR\x04base\x12.\n" +
	"\bproducts\x18\x02 \x03(\v2\x12.productpb.ProductR\bproducts\"\xe4\x02\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x18\n" +
	"\apicInfo\x18\x06 \x01(\tR\apicInfo\x12\x1e\n" +
	"\n" +
	"dimensions\x18\a \x01(\tR\n" +
	"dimensions\x12\x1a\n" +
	"\bmaterial\x18\b \x01(\tR\bmaterial\x12\x16\n" +
	"\x06weight\x18\t \x01(\tR\x06weight\x12\x1a\n" +
	"\bcapacity\x18\n" +
	" \x01(\tR\bcapacity\x12*\n" +
	"\x10careInstructions\x18\v \x01(\tR\x10careInstructions\x12&\n" +
	"\x0elatestEditorId\x18\f \x01(\x05R\x0elatestEditorId\"\xa3\x03\n" +
	"\x15CreateProductResponse\x12,\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x17.productpb.BaseResponseR\x04base\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x18\n" +
	"\apicInfo\x18\x06 \x01(\tR\apicInfo\x12\x1e\n" +
	"\n" +
	"dimensions\x18\a \x01(\tR\n" +
	"dimensions\x12\x1a\n" +
	"\bmaterial\x18\b \x01(\tR\bmaterial\x12\x16\n" +
	"\x06weight\x18\t \x01(\tR\x06weight\x12\x1a\n" +
	"\bcapacity\x18\n" +
	" \x01(\tR\bcapacity\x12*\n" +
	"\x10careInstructions\x18\v \x01(\tR\x10careInstructions\x12\x0e\n" +
	"\x02id\x18\f \x01(\x03R\x02id\x12&\n" +
	"\x0elatestEditorId\x18\r \x01(\x05R\x0elatestEditorId*|\n" +
	"\fResponseCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\xf4\x03\x12\x12\n" +
	"\rINVALID_PARAM\x10\x90\x03\x12\x0e\n" +
	"\tNOT_FOUND\x10\x94\x03\x12\r\n" +
	"\bCONFLICT\x10\x99\x03\x12\x17\n" +
	"\x12INSUFFICIENT_STOCK\x10\xa1\x1f2\x9e\x02\n" +
	"\x0eProductService\x12a\n" +
	"\x12UpdateStockWithCAS\x12$.productpb.UpdateStockWithCASRequest\x1a%.productpb.UpdateStockWithCASResponse\x12U\n" +
	"\x0eGetProductList\x12 .productpb.GetProductListRequest\x1a!.productpb.GetProductListResponse\x12R\n" +
	"\rCreateProduct\x12\x1f.productpb.CreateProductRequest\x1a .productpb.CreateProductResponseB\x16Z\x14/productpb;productpbb\x06proto3"

var (
	file_proto_product_proto_rawDescOnce sync.Once
	file_proto_product_proto_rawDescData []byte
)

func file_proto_product_proto_rawDescGZIP() []byte {
	file_proto_product_proto_rawDescOnce.Do(func() {
		file_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)))
	})
	return file_proto_product_proto_rawDescData
}

var file_proto_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_product_proto_goTypes = []any{
	(ResponseCode)(0),                  // 0: productpb.ResponseCode
	(*BaseResponse)(nil),               // 1: productpb.BaseResponse
	(*UpdateStockWithCASRequest)(nil),  // 2: productpb.UpdateStockWithCASRequest
	(*UpdateStockWithCASResponse)(nil), // 3: productpb.UpdateStockWithCASResponse
	(*Product)(nil),                    // 4: productpb.Product
	(*GetProductListRequest)(nil),      // 5: productpb.GetProductListRequest
	(*GetProductListResponse)(nil),     // 6: productpb.GetProductListResponse
	(*CreateProductRequest)(nil),       // 7: productpb.CreateProductRequest
	(*CreateProductResponse)(nil),      // 8: productpb.CreateProductResponse
}
var file_proto_product_proto_depIdxs = []int32{
	1, // 0: productpb.UpdateStockWithCASResponse.base:type_name -> productpb.BaseResponse
	1, // 1: productpb.GetProductListResponse.base:type_name -> productpb.BaseResponse
	4, // 2: productpb.GetProductListResponse.products:type_name -> productpb.Product
	1, // 3: productpb.CreateProductResponse.base:type_name -> productpb.BaseResponse
	2, // 4: productpb.ProductService.UpdateStockWithCAS:input_type -> productpb.UpdateStockWithCASRequest
	5, // 5: productpb.ProductService.GetProductList:input_type -> productpb.GetProductListRequest
	7, // 6: productpb.ProductService.CreateProduct:input_type -> productpb.CreateProductRequest
	3, // 7: productpb.ProductService.UpdateStockWithCAS:output_type -> productpb.UpdateStockWithCASResponse
	6, // 8: productpb.ProductService.GetProductList:output_type -> productpb.GetProductListResponse
	8, // 9: productpb.ProductService.CreateProduct:output_type -> productpb.CreateProductResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_product_proto_init() }
func file_proto_product_proto_init() {
	if File_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_proto_goTypes,
		DependencyIndexes: file_proto_product_proto_depIdxs,
		EnumInfos:         file_proto_product_proto_enumTypes,
		MessageInfos:      file_proto_product_proto_msgTypes,
	}.Build()
	File_proto_product_proto = out.File
	file_proto_product_proto_goTypes = nil
	file_proto_product_proto_depIdxs = nil
}
