// Code generated by MockGen. DO NOT EDIT.
// Source: dao/productDao.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dao "github.com/sw5005-sus/ceramicraft-commodity-mservice/server/repository/dao"
	model "github.com/sw5005-sus/ceramicraft-commodity-mservice/server/repository/model"
	gomock "github.com/golang/mock/gomock"
)

// MockProductDao is a mock of ProductDao interface.
type MockProductDao struct {
	ctrl     *gomock.Controller
	recorder *MockProductDaoMockRecorder
}

// MockProductDaoMockRecorder is the mock recorder for MockProductDao.
type MockProductDaoMockRecorder struct {
	mock *MockProductDao
}

// NewMockProductDao creates a new mock instance.
func NewMockProductDao(ctrl *gomock.Controller) *MockProductDao {
	mock := &MockProductDao{ctrl: ctrl}
	mock.recorder = &MockProductDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductDao) EXPECT() *MockProductDaoMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductDao) CreateProduct(ctx context.Context, product *model.Product) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, product)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductDaoMockRecorder) CreateProduct(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductDao)(nil).CreateProduct), ctx, product)
}

// GetProductByID mocks base method.
func (m *MockProductDao) GetProductByID(ctx context.Context, id int) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductDaoMockRecorder) GetProductByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductDao)(nil).GetProductByID), ctx, id)
}

// GetProductByIDs mocks base method.
func (m *MockProductDao) GetProductByIDs(ctx context.Context, ids []int) ([]*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByIDs", ctx, ids)
	ret0, _ := ret[0].([]*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByIDs indicates an expected call of GetProductByIDs.
func (mr *MockProductDaoMockRecorder) GetProductByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByIDs", reflect.TypeOf((*MockProductDao)(nil).GetProductByIDs), ctx, ids)
}

// ListProduct mocks base method.
func (m *MockProductDao) ListProduct(ctx context.Context, q dao.ListProductQuery) ([]*model.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProduct", ctx, q)
	ret0, _ := ret[0].([]*model.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProduct indicates an expected call of ListProduct.
func (mr *MockProductDaoMockRecorder) ListProduct(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProduct", reflect.TypeOf((*MockProductDao)(nil).ListProduct), ctx, q)
}

// UpdateProduct mocks base method.
func (m *MockProductDao) UpdateProduct(ctx context.Context, product *model.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductDaoMockRecorder) UpdateProduct(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductDao)(nil).UpdateProduct), ctx, product)
}

// UpdateProductStatus mocks base method.
func (m *MockProductDao) UpdateProductStatus(ctx context.Context, id, status int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductStatus indicates an expected call of UpdateProductStatus.
func (mr *MockProductDaoMockRecorder) UpdateProductStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductStatus", reflect.TypeOf((*MockProductDao)(nil).UpdateProductStatus), ctx, id, status)
}

// UpdateProductStock mocks base method.
func (m *MockProductDao) UpdateProductStock(ctx context.Context, id, stock int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductStock", ctx, id, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductStock indicates an expected call of UpdateProductStock.
func (mr *MockProductDaoMockRecorder) UpdateProductStock(ctx, id, stock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductStock", reflect.TypeOf((*MockProductDao)(nil).UpdateProductStock), ctx, id, stock)
}

// UpdateStockWithCAS mocks base method.
func (m *MockProductDao) UpdateStockWithCAS(ctx context.Context, id, version, newStock int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStockWithCAS", ctx, id, version, newStock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStockWithCAS indicates an expected call of UpdateStockWithCAS.
func (mr *MockProductDaoMockRecorder) UpdateStockWithCAS(ctx, id, version, newStock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStockWithCAS", reflect.TypeOf((*MockProductDao)(nil).UpdateStockWithCAS), ctx, id, version, newStock)
}
