// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sw5005-sus/ceramicraft-commodity-mservice/server/repository/dao (interfaces: ProductDao)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dao "github.com/sw5005-sus/ceramicraft-commodity-mservice/server/repository/dao"
	model "github.com/sw5005-sus/ceramicraft-commodity-mservice/server/repository/model"
)

// MockProductDao is a mock of ProductDao interface.
type MockProductDao struct {
	ctrl     *gomock.Controller
	recorder *MockProductDaoMockRecorder
}

// MockProductDaoMockRecorder is the mock recorder for MockProductDao.
type MockProductDaoMockRecorder struct {
	mock *MockProductDao
}

// NewMockProductDao creates a new mock instance.
func NewMockProductDao(ctrl *gomock.Controller) *MockProductDao {
	mock := &MockProductDao{ctrl: ctrl}
	mock.recorder = &MockProductDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductDao) EXPECT() *MockProductDaoMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductDao) CreateProduct(arg0 context.Context, arg1 *model.Product) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductDaoMockRecorder) CreateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductDao)(nil).CreateProduct), arg0, arg1)
}

// GetProductByID mocks base method.
func (m *MockProductDao) GetProductByID(arg0 context.Context, arg1 int) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductDaoMockRecorder) GetProductByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductDao)(nil).GetProductByID), arg0, arg1)
}

// GetProductByIDs mocks base method.
func (m *MockProductDao) GetProductByIDs(arg0 context.Context, arg1 []int) ([]*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByIDs", arg0, arg1)
	ret0, _ := ret[0].([]*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByIDs indicates an expected call of GetProductByIDs.
func (mr *MockProductDaoMockRecorder) GetProductByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByIDs", reflect.TypeOf((*MockProductDao)(nil).GetProductByIDs), arg0, arg1)
}

// ListProduct mocks base method.
func (m *MockProductDao) ListProduct(arg0 context.Context, arg1 dao.ListProductQuery) ([]*model.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProduct", arg0, arg1)
	ret0, _ := ret[0].([]*model.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProduct indicates an expected call of ListProduct.
func (mr *MockProductDaoMockRecorder) ListProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProduct", reflect.TypeOf((*MockProductDao)(nil).ListProduct), arg0, arg1)
}

// UpdateProduct mocks base method.
func (m *MockProductDao) UpdateProduct(arg0 context.Context, arg1 *model.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductDaoMockRecorder) UpdateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductDao)(nil).UpdateProduct), arg0, arg1)
}

// UpdateProductStatus mocks base method.
func (m *MockProductDao) UpdateProductStatus(arg0 context.Context, arg1, arg2 int, arg3 *model.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductStatus indicates an expected call of UpdateProductStatus.
func (mr *MockProductDaoMockRecorder) UpdateProductStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductStatus", reflect.TypeOf((*MockProductDao)(nil).UpdateProductStatus), arg0, arg1, arg2, arg3)
}

// UpdateProductStock mocks base method.
func (m *MockProductDao) UpdateProductStock(arg0 context.Context, arg1, arg2, arg3 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductStock", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductStock indicates an expected call of UpdateProductStock.
func (mr *MockProductDaoMockRecorder) UpdateProductStock(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductStock", reflect.TypeOf((*MockProductDao)(nil).UpdateProductStock), arg0, arg1, arg2, arg3)
}

// UpdateStockWithCAS mocks base method.
func (m *MockProductDao) UpdateStockWithCAS(arg0 context.Context, arg1, arg2, arg3, arg4 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStockWithCAS", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStockWithCAS indicates an expected call of UpdateStockWithCAS.
func (mr *MockProductDaoMockRecorder) UpdateStockWithCAS(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStockWithCAS", reflect.TypeOf((*MockProductDao)(nil).UpdateStockWithCAS), arg0, arg1, arg2, arg3, arg4)
}
